### ISSUE TITLE
[Bug?] skinColor.png not loaded at all

### ISSUE THREAD

**Issue by VaelophisNyx** [MartyrPher/GetGlam#2]
Should have ~160 colors more than vanilla
somehow only have the vanilla skin colors?

File structure is exactly as the documentation told me to set it up

**Comment by Traehgniw** [comment]
I tested this with adding smaller skin colour set - specifically one of the skin colour sets from the old Content Patcher/Kisekae/XNB replacer one - and it worked! So it seems like you need to add it as several smaller packs, not one huge pack.

**Comment by Traehgniw** [comment]
Oh, more interestingness: when testing this, note that skins and favourites don't work if the save is brand-new. Like, I started a fresh save, went to change the farmer's skin to one of the ones I'd just added, and it didn't work. Closing and reopening the game made it work.

hypothesis: it doesn't like really large skin packs _or_ that split-second flash of Spring Zero you get when you start a new save

**Comment by cola98765** [comment]
I had this problem also. I used save-as in paint to set format again as PNG and ~~it worked fine then~~ (I was adding 72 colors) it still tended to fail actually loading them. It didn't threw an error, and you could select all of them, bu they did not do anything.

**Comment by MartyrPher** [comment]
I'm going to work on a rewrite and try and clean up the code base for maintainability. Any way to post the failing skincolor.png in here so I can recreate this issue?

**Comment by cola98765** [comment]
I simplified mine skincolor.png, and I accidentally overwritten the failing one, and now when I recreated it, it works fine... Thanks for trying, I guess.

**Comment by Veritrix** [comment]
I'm having problems with GetGlam loading skinColor packs. As in they won't load at all. I'm using one that's the same amount as the vanilla/default png.

[[GG] - Starkissed Skins.zip](https://github.com/MartyrPher/GetGlam/files/5937742/GG.-.Starkissed.Skins.zip)

The only thing that shows in GG's menu is the default/base skins. I don't have any other mod changing or altering the skincolor for the farmer.
